### ISSUE TITLE
Release of the Nuget Package

### ISSUE THREAD

**Issue by SeriousM** [envkey/envkey-dotnet#1]
Hi @danenania,

the package is now done and as pre-prelease published.
https://www.nuget.org/packages/EnvKey

You wanted to do some testing and final adjustments, now is the time :)

Please create a user on nuget.org so I can add you as owner.

Best, Bernhard

**Comment by danenania** [comment]
Great! I created a nuget.org account - username is envkey.

**Comment by SeriousM** [comment]
> Great! I created a nuget.org account - username is envkey.

well, you're not done with the user setup yet..
> Sorry, 'envkey' hasn't verified their email account yet and we cannot proceed with the request.

**Comment by danenania** [comment]
Oops - ok, just verified.

On Thu, Apr 19, 2018 at 2:25 AM, Bernhard Millauer <notifications@github.com

**Comment by SeriousM** [comment]
Are you or one of your teammates familiar with .net development?

**Comment by danenania** [comment]
@SeriousM Not really. I've played with it a little, but no real experience otherwise.

**Comment by SeriousM** [comment]
@danenania: do you have any objections about the current state of this nuget package?
If not I would deploy a release version of the package.
Could you then please update the envkey website to point to the c# package?

**Comment by danenania** [comment]
Hey @SeriousM , thanks again for the work you put into this and sorry for the delay--just had a chance to take a look.

A few things come to mind:

1 - Can we get the load into a single line? Or even better, can it be run automatically when the package is included? I don't know if the latter would make sense in a .net context, but at the very least, instead of:

```
var envKey  = new EnvKeyConfig();
var success = envKey.TryLoadIntoEnvironment();
```

I would much prefer something simpler and shorter (and more consistent with the other libs) like:

```
EnvKey.Load();
```

2 -Along those lines, I would much prefer that if the `EnvKey.load()` call fails, that it raises an error instead of returning false. In the case that the load fails, that process is in a bad state and should fail loudly asap rather than continuing on to potentially cause trouble. 

3 - In order to provide a mechanism for overriding EnvKey vars locally, the package should only set an environment variable if it isn't already defined.

Also to confirm, this will be windows-only? Since my understanding is the vast majority of .net users are on windows (is that right?), I think that's fine for now, but it should be made clear in the README.

Speaking of the README, it needs more fleshing out--I'm happy to help with this part. I'd like it to have a similar level of detail as the other libs (see https://github.com/envkey/envkey-node for reference).

**Comment by SeriousM** [comment]
Thank you for the input!

@1: In .net we tend to avoid static objects so it should be something like
```cs
new EnvKeyConfig().Load();
```

Since the namespace is already called EnvKey it's not allowed to name a object the same as the enclosing namespace to avoid confusion. I guess EnvKeyConfig is ok then.

@2: sure, I will throw an exception to indicate the problem.

@3: as you like. I will change it to only patch missing values

@4: I will update the readme to indicate the windows-only support for now.

@5: that would be great, I'm bad at marketing :)

I will report back once done.

**Comment by SeriousM** [comment]
@1, @2: done now. I moved the Try* methods into extensions so they're available if needed. The api is now as simple as `new EnvKeyConfig().Load()`.
@3: only missing keys now added
@4: done
@5: please update the readme and add some information to the envkey.com page

May I release the package now?

**Comment by danenania** [comment]
Looks great @SeriousM! Yep, you can go ahead and release. I'll update the readme and add a link on the website. I'll also do some more marketing of the package early next week (twitter, reddit, fb groups, Slack groups). Do you know of any other places we should post it?

**Comment by SeriousM** [comment]
I'm not a marketing guy :).
Will you update the envkey.com page?
